//! Service & init-system integration (US-DEP-04).
//!
//! Generates and installs a **systemd user service** so the hub (and its
//! workflow scheduler + API) can run headless in the background, plus a
//! cron line for cron-only systems. No external dependencies: everything
//! is plain string generation, so it works for any init that can consume
//! a unit file or a crontab line.
//!
//! Usage:
//! ```text
//! tui-op-hub --print-unit         # show the unit file on stdout
//! tui-op-hub --install-service    # write + daemon-reload + enable (best effort)
//! tui-op-hub --uninstall-service  # disable + remove (best effort)
//! tui-op-hub --headless           # run without the TUI (daemon mode)
//! ```

use std::path::PathBuf;

/// The systemd unit name.
pub const SERVICE_NAME: &str = "tui-op-hub";

fn dirs_home() -> PathBuf {
    std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| PathBuf::from("/"))
}

/// Where the user unit file lives.
pub fn unit_path() -> PathBuf {
    unit_path_in(&dirs_home())
}

/// `unit_path` for an explicit home directory (used by tests and setup).
pub fn unit_path_in(home: &std::path::Path) -> PathBuf {
    home.join(".config/systemd/user")
        .join(format!("{SERVICE_NAME}.service"))
}

/// The environment file the unit references.
pub fn env_file_path() -> PathBuf {
    env_file_path_in(&dirs_home())
}

/// `env_file_path` for an explicit home directory.
pub fn env_file_path_in(home: &std::path::Path) -> PathBuf {
    home.join(".config/tui-op-hub/env")
}

/// Generate a fresh 32-byte master key, base64-encoded.
fn generate_key_b64() -> String {
    use base64::Engine as _;
    let mut key = [0u8; 32];
    getrandom::getrandom(&mut key).expect("system RNG unavailable");
    base64::engine::general_purpose::STANDARD.encode(key)
}

/// Create `~/.config/tui-op-hub/env` with a generated master key (mode 600)
/// if it does not exist. Returns `Ok(true)` when a new file was created.
/// Never overwrites an existing file, so re-running setup is safe.
pub fn ensure_env_file_in(home: &std::path::Path) -> std::io::Result<bool> {
    let path = env_file_path_in(home);
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(
        &path,
        format!(
            "# Generated by tui-op-hub --install-service. Do not commit.\nTUI_OP_HUB_SECRETS_KEY={}\n",
            generate_key_b64()
        ),
    )?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
    }
    Ok(true)
}

/// Resolve the current executable path for `ExecStart`.
fn current_exe() -> String {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.to_str().map(str::to_string))
        .unwrap_or_else(|| "/usr/local/bin/tui-op-hub".to_string())
}

/// Generate the systemd **user** unit file content.
///
/// The service runs the hub headless (no TUI) so the workflow scheduler and
/// REST API stay available in the background. `TUI_OP_HUB_SECRETS_KEY` is
/// intentionally NOT written into the unit; provide it with
/// `systemctl --user set-environment` or an `EnvironmentFile=` instead.
pub fn systemd_user_unit() -> String {
    let exe = current_exe();
    format!(
        r#"[Unit]
Description=TUI-OP-HUB operations hub (headless)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={exe} --headless
Restart=on-failure
RestartSec=3
# Master key lives in this environment file (created by --install-service,
# mode 600). Regenerate: delete the file and re-run --install-service.
EnvironmentFile=%h/.config/tui-op-hub/env

[Install]
WantedBy=default.target
"#
    )
}

/// Generate a cron line that keeps the hub running headless (restarts it if
/// it died). For cron-only systems without systemd.
pub fn cron_line() -> String {
    let exe = current_exe();
    format!("* * * * * pgrep -f '{exe} --headless' >/dev/null || {exe} --headless # tui-op-hub")
}

/// Full setup against an explicit home: env file (generated once) + unit
/// file + best-effort `systemctl --user daemon-reload` and `enable --now`.
/// Idempotent, safe to re-run on every release install.
pub fn install_service_in(home: &std::path::Path) -> std::io::Result<PathBuf> {
    ensure_env_file_in(home)?;
    let path = unit_path_in(home);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&path, systemd_user_unit())?;
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status();
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "enable", "--now", SERVICE_NAME])
        .status();
    Ok(path)
}

/// Write the unit file and try to enable the service (best effort: a missing
/// `systemctl` is not an error, the file is still written for other inits).
pub fn install_service() -> std::io::Result<PathBuf> {
    install_service_in(&dirs_home())
}

/// Disable and remove the unit file (best effort). The env file is kept:
/// deleting a master key silently would make existing secrets undecryptable.
pub fn uninstall_service() -> std::io::Result<()> {
    uninstall_service_in(&dirs_home())
}

/// `uninstall_service` for an explicit home directory.
pub fn uninstall_service_in(home: &std::path::Path) -> std::io::Result<()> {
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "disable", "--now", SERVICE_NAME])
        .status();
    let path = unit_path_in(home);
    if path.exists() {
        std::fs::remove_file(&path)?;
    }
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .status();
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_file_contains_required_sections() {
        let unit = systemd_user_unit();
        assert!(unit.contains("[Unit]"));
        assert!(unit.contains("[Service]"));
        assert!(unit.contains("[Install]"));
        assert!(unit.contains("ExecStart="));
        assert!(unit.contains("--headless"));
        assert!(unit.contains("Restart=on-failure"));
        assert!(unit.contains("WantedBy=default.target"));
    }

    #[test]
    fn unit_file_does_not_embed_secrets_key() {
        // The real key must never be persisted into an active directive.
        // (Mentioning it in a comment is fine.)
        let unit = systemd_user_unit();
        let active = unit
            .lines()
            .filter(|l| !l.trim_start().starts_with('#'))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(!active.contains("TUI_OP_HUB_SECRETS_KEY="));
    }

    #[test]
    fn cron_line_references_headless_binary() {
        let line = cron_line();
        assert!(line.contains("--headless"));
        assert!(line.starts_with("* * * * *"));
        assert!(line.contains("tui-op-hub"));
    }

    #[test]
    fn unit_file_references_env_file() {
        let unit = systemd_user_unit();
        assert!(unit.contains("EnvironmentFile=%h/.config/tui-op-hub/env"));
    }

    #[test]
    fn ensure_env_file_creates_valid_key_once() {
        let home = std::env::temp_dir().join(format!("tui-op-hub-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&home);

        // First call creates the file
        assert!(ensure_env_file_in(&home).unwrap());
        let path = env_file_path_in(&home);
        let content = std::fs::read_to_string(&path).unwrap();

        // Key line parses as 32 bytes of base64
        let key_line = content
            .lines()
            .find(|l| l.starts_with("TUI_OP_HUB_SECRETS_KEY="))
            .expect("key line present");
        let b64 = key_line.trim_start_matches("TUI_OP_HUB_SECRETS_KEY=");
        use base64::Engine as _;
        let decoded = base64::engine::general_purpose::STANDARD
            .decode(b64)
            .expect("valid base64");
        assert_eq!(decoded.len(), 32);

        // Mode 600 on unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600);
        }

        // Second call is a no-op (never clobbers the key)
        assert!(!ensure_env_file_in(&home).unwrap());
        let content2 = std::fs::read_to_string(&path).unwrap();
        assert_eq!(content, content2);

        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn install_service_in_writes_unit_and_env() {
        let home = std::env::temp_dir().join(format!("tui-op-hub-install-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&home);

        let path = install_service_in(&home).unwrap();
        assert_eq!(path, unit_path_in(&home));
        assert!(path.exists(), "unit file written");
        assert!(env_file_path_in(&home).exists(), "env file written");

        let unit = std::fs::read_to_string(&path).unwrap();
        assert!(unit.contains("--headless"));

        // Idempotent: re-running keeps the same key
        let key_before = std::fs::read_to_string(env_file_path_in(&home)).unwrap();
        let _ = install_service_in(&home);
        let key_after = std::fs::read_to_string(env_file_path_in(&home)).unwrap();
        assert_eq!(key_before, key_after);

        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn unit_path_is_under_systemd_user_dir() {
        let p = unit_path();
        assert!(p.to_string_lossy().contains(".config/systemd/user/"));
        assert!(p.to_string_lossy().ends_with("tui-op-hub.service"));
    }
}
